"""
Data models for the Capability Router subsystem.
"""

from dataclasses import dataclass, field
from enum import Enum


class CapabilityType(Enum):
    """The type of a registered capability."""
    CORE = "core"            # Memory, Workspace, Knowledge
    TOOL = "tool"            # Browser, File, Windows, Git
    AGENT = "agent"          # Coding Agent, Internet Agent
    INTEGRATION = "integration"  # Email, Calendar, Discord


@dataclass(frozen=True)
class Capability:
    """Metadata describing a registered subsystem or tool."""
    
    name: str
    description: str
    type: CapabilityType
    requires_internet: bool = False
    requires_vision: bool = False
    requires_voice: bool = False
    cost_weight: int = 1


@dataclass(frozen=True)
class CapabilityPlan:
    """The immutable execution plan generated by the Intelligent Capability Router."""
    
    reasoning_model: str
    required_capabilities: list[str] = field(default_factory=list)
    required_tools: list[str] = field(default_factory=list)
    
    requires_planner: bool = False
    requires_memory: bool = False
    requires_script: bool = False
    requires_storyboard: bool = False
    requires_images: bool = False
    requires_voice: bool = False
    requires_video: bool = False
    requires_music: bool = False
    requires_subtitles: bool = False
    requires_thumbnail: bool = False
    requires_seo: bool = False
    requires_publishing: bool = False
    requires_analytics: bool = False
    
    # Internal capabilities
    requires_knowledge: bool = False
    requires_workspace: bool = False
    requires_internet: bool = False
    requires_automation: bool = False
    requires_scripting: bool = False
    requires_animation: bool = False
    requires_project_management: bool = False
    requires_image_generation: bool = False
    requires_agents: bool = False
    requires_execution: bool = False
    
    estimated_complexity: str = "low"  # low, medium, high
    estimated_cost: str = "low"
    estimated_latency: str = "low"
    confidence: float = 1.0

    # LLM-extracted mission style (e.g. "educational", "storytelling", "podcast")
    # Used by Agent._handle_mission() instead of substring scanning.
    style: str = "storytelling"
