"""
Model Selection Logic for Capability Routing.
"""

from collections.abc import Iterable

from core.capability.exceptions import ModelSelectionError
from core.capability.models import CapabilityPlan
from core.capability.profiles import ModelProfile


class ModelSelector:
    """Selects the best model to execute the capability plan."""

    def __init__(self, available_profiles: Iterable[ModelProfile]) -> None:
        self._profiles = list(available_profiles)
        if not self._profiles:
            raise ValueError("ModelSelector initialized with no profiles.")

    def select(self, plan: CapabilityPlan) -> ModelProfile:
        """Select a model that fulfills the requirements of the plan.
        
        Args:
            plan: The generated capability plan.
            
        Returns:
            The selected ModelProfile.
            
        Raises:
            ModelSelectionError: If no model can fulfill the plan.
        """
        candidates = self._profiles
        
        # 1. Filter by explicit model request if generated by the router
        if plan.reasoning_model and plan.reasoning_model != "auto":
            exact_match = next((p for p in candidates if p.name == plan.reasoning_model), None)
            if exact_match:
                return exact_match
                
        # 2. Filter by complexity
        if plan.estimated_complexity == "high":
            candidates = [p for p in candidates if p.reasoning >= 8]
        elif plan.estimated_complexity == "medium":
            candidates = [p for p in candidates if p.reasoning >= 5]
            
        # 3. Filter by specific capability needs
        if "vision" in plan.required_capabilities:
            candidates = [p for p in candidates if p.vision]
            
        if "voice" in plan.required_capabilities:
            candidates = [p for p in candidates if p.voice]
            
        if plan.requires_agents:
            # Coding agents need strong coding models
            candidates = [p for p in candidates if p.coding >= 8]
            
        if not candidates:
            # Fallback to best available profile if strict filters eliminated all profiles
            if self._profiles:
                return max(self._profiles, key=lambda p: (p.reasoning, p.coding))
            raise ModelSelectionError(
                f"No suitable model found for plan with complexity={plan.estimated_complexity} "
                f"and capabilities={plan.required_capabilities}"
            )
            
        # 4. Score and select the best candidate
        # For now, pick the cheapest one that meets the bar, breaking ties by latency
        candidates.sort(key=lambda p: (p.cost.value, p.latency.value))
        
        return candidates[0]
