"""
World Model — data models.

All models are immutable (frozen dataclasses) so snapshots can be safely
passed across threads without risk of mutation.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Optional


class WindowFocusState(StrEnum):
    FOCUSED  = "focused"
    RECENT   = "recent"
    UNKNOWN  = "unknown"


class GitRepoStatus(StrEnum):
    CLEAN   = "clean"
    DIRTY   = "dirty"
    UNKNOWN = "unknown"


class ProcessStatus(StrEnum):
    RUNNING  = "running"
    SLEEPING = "sleeping"
    ZOMBIE   = "zombie"
    UNKNOWN  = "unknown"


# ---------------------------------------------------------------------------
# Workspace
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class RegisteredWorkspace:
    """A user-trusted workspace folder."""
    id: str
    path: str                    # absolute filesystem path
    name: str                    # human-readable label
    language: Optional[str] = None  # primary programming language
    registered_at: str = ""


# ---------------------------------------------------------------------------
# Git
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class GitStatus:
    """Current state of a git repository."""
    workspace_id: str
    repo_path: str
    current_branch: str = "unknown"
    is_dirty: bool = False
    status: GitRepoStatus = GitRepoStatus.UNKNOWN
    modified_files: list[str] = field(default_factory=list)
    staged_files: list[str] = field(default_factory=list)
    recent_commits: list[str] = field(default_factory=list)   # short SHA + message


# ---------------------------------------------------------------------------
# Processes
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ProcessInfo:
    """A snapshot of a running process."""
    pid: int
    name: str
    status: ProcessStatus = ProcessStatus.UNKNOWN
    cpu_percent: float = 0.0
    memory_mb: float = 0.0
    is_ai_process: bool = False  # heuristic: llama, ollama, python, ffmpeg, etc.


# ---------------------------------------------------------------------------
# Window / Application focus
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class WindowInfo:
    """Currently focused or recently used application window."""
    title: str
    application: str
    focus_state: WindowFocusState = WindowFocusState.UNKNOWN
    workspace_path: Optional[str] = None   # if IDE — detected project path


# ---------------------------------------------------------------------------
# Active Missions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ActiveMissionRef:
    """Light reference to a mission currently in-progress."""
    mission_id: str
    title: str
    progress: float = 0.0   # 0–100


# ---------------------------------------------------------------------------
# World State (immutable snapshot)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class WorldState:
    """
    An immutable snapshot of the user's current working environment.
    Generated by WorldSnapshot and injected into planning context.
    """
    snapshot_id: str = field(default_factory=lambda: f"ws_{uuid.uuid4().hex[:8]}")
    captured_at: str = ""

    # Workspace
    registered_workspaces: list[RegisteredWorkspace] = field(default_factory=list)
    active_workspace: Optional[RegisteredWorkspace] = None

    # Git
    git_statuses: list[GitStatus] = field(default_factory=list)

    # Processes
    running_processes: list[ProcessInfo] = field(default_factory=list)

    # Window / focus
    focused_window: Optional[WindowInfo] = None
    recent_windows: list[WindowInfo] = field(default_factory=list)

    # Active missions
    active_missions: list[ActiveMissionRef] = field(default_factory=list)

    def format_for_prompt(self) -> str:
        """Serialise relevant portions of the world state into a plain-text block."""
        lines = ["## Current World State"]

        if self.active_workspace:
            lines.append(f"\n**Active Workspace**: {self.active_workspace.name} ({self.active_workspace.path})")
            if self.active_workspace.language:
                lines.append(f"  Language: {self.active_workspace.language}")

        if self.git_statuses:
            lines.append("\n**Git Repositories**:")
            for git in self.git_statuses:
                dirty = " (dirty)" if git.is_dirty else " (clean)"
                lines.append(f"  • [{git.current_branch}]{dirty} {git.repo_path}")
                if git.modified_files:
                    lines.append(f"    Modified: {', '.join(git.modified_files[:5])}")
                if git.recent_commits:
                    lines.append(f"    Last commit: {git.recent_commits[0]}")

        if self.focused_window:
            lines.append(f"\n**Focused Application**: {self.focused_window.application} — {self.focused_window.title}")

        if self.active_missions:
            lines.append("\n**Running Missions**:")
            for m in self.active_missions:
                lines.append(f"  • {m.title} ({m.progress:.0f}%)")

        ai_procs = [p for p in self.running_processes if p.is_ai_process]
        if ai_procs:
            lines.append("\n**AI Processes**:")
            for p in ai_procs:
                lines.append(f"  • {p.name} [PID {p.pid}] CPU={p.cpu_percent:.1f}% MEM={p.memory_mb:.0f}MB")

        return "\n".join(lines)
