"""
Production ComfyUI Animation Adapter.
"""
import logging

from .models import AnimationParameters
from .exceptions import AnimationAdapterError
from core.integrations.comfyui import (
    ComfyUIClient,
    ComfyUIWebSocket,
    ComfyUIDownloader,
    ComfyUIHealthCheck,
    ComfyUIWorkflow
)

logger = logging.getLogger(__name__)

class ProductionComfyUIAnimationAdapter:
    """Production Adapter for ComfyUI Animation Workflows."""
    
    def __init__(self, host: str = "127.0.0.1", port: int = 8188):
        self.client = ComfyUIClient(host, port)
        self.health_check = ComfyUIHealthCheck(self.client)
        self.websocket = ComfyUIWebSocket(self.client)
        self.downloader = ComfyUIDownloader(self.client)
        
    def generate(self, params: AnimationParameters) -> bytes:
        if not params.motion_prompt:
            raise AnimationAdapterError("ComfyUI requires a motion_prompt")
            
        logger.info("Executing animation generation via Production ComfyUI...")
        
        # 1. Health check
        self.health_check.check()
        
        # 2. Build mock payload for AnimateDiff
        workflow_json = {
            "3": {
                "inputs": {
                    "text": params.motion_prompt
                },
                "class_type": "CLIPTextEncode"
            },
            # Dummy node to satisfy prompt structure
            "8": {
                "inputs": {
                    "samples": ["3", 0]
                },
                "class_type": "VAEDecode"
            }
        }
        workflow = ComfyUIWorkflow(nodes=workflow_json)
        
        # 3. Queue prompt
        prompt_response = self.client.queue_prompt(workflow)
        prompt_id = prompt_response.prompt_id
        
        # 4. Wait for completion
        # Allow a longer timeout for animations
        self.websocket.wait_for_completion(prompt_id, timeout_sec=900)
        
        # 5. Fetch history & download
        history = self.client.get_history(prompt_id)
        outputs = self.downloader.download_outputs(history)
        
        if not outputs:
            raise AnimationAdapterError("No outputs generated by ComfyUI.")
            
        return outputs[0].data
