from enum import StrEnum


class MetricType(StrEnum):
    TASK_SUCCESS = "TASK_SUCCESS"
    WORKFLOW_SUCCESS = "WORKFLOW_SUCCESS"
    MISSION_COMPLETION = "MISSION_COMPLETION"
    LATENCY = "LATENCY"
    PLANNING_TIME = "PLANNING_TIME"
    TOOL_USAGE = "TOOL_USAGE"
    SKILL_USAGE = "SKILL_USAGE"
    PLUGIN_USAGE = "PLUGIN_USAGE"
    MEMORY_ACCURACY = "MEMORY_ACCURACY"
    VOICE_ACCURACY = "VOICE_ACCURACY"
    VISION_ACCURACY = "VISION_ACCURACY"
    AGENT_COLLABORATION = "AGENT_COLLABORATION"
    GOAL_COMPLETION = "GOAL_COMPLETION"
    PROVIDER_RELIABILITY = "PROVIDER_RELIABILITY"

class OptimizationCategory(StrEnum):
    SKILL_CONFIDENCE = "SKILL_CONFIDENCE"
    PLANNER_WEIGHT = "PLANNER_WEIGHT"
    PROVIDER_PRIORITY = "PROVIDER_PRIORITY"
    WORKFLOW_RANKING = "WORKFLOW_RANKING"
    TOOL_PREFERENCE = "TOOL_PREFERENCE"
    RETRY_TUNING = "RETRY_TUNING"
    CACHE_TUNING = "CACHE_TUNING"

class RecommendationStatus(StrEnum):
    PENDING = "PENDING"
    APPLIED = "APPLIED"
    REJECTED = "REJECTED"
    REVERTED = "REVERTED"

class TrendDirection(StrEnum):
    IMPROVING = "IMPROVING"
    DEGRADING = "DEGRADING"
    STABLE = "STABLE"

class PolicyAction(StrEnum):
    ALLOW = "ALLOW"
    BLOCK_OSCILLATION = "BLOCK_OSCILLATION"
    BLOCK_UNSAFE = "BLOCK_UNSAFE"
    BLOCK_CONFLICT = "BLOCK_CONFLICT"
