import builtins
import os

from core.models.primitives import Identifier

from .interfaces import IDocumentParser, IIndexer


class DirectoryIndexer(IIndexer):
    """Recursively traverses folders to queue files for ingestion."""

    def __init__(self, parsers: builtins.list[IDocumentParser]) -> None:
        self._parsers = parsers

    def index_folder(self, folder_path: str) -> builtins.list[Identifier]:
        if not os.path.exists(folder_path):
            raise FileNotFoundError(f"Folder {folder_path} not found.")
            
        queued_files = []
        for root, _, files in os.walk(folder_path):
            for file in files:
                file_path = os.path.join(root, file)
                if self._get_parser(file_path):
                    # We just track the paths to be ingested later.
                    # A true identifier might be generated by ingestion.
                    # Here we return raw paths wrapped loosely (just for the contract).
                    queued_files.append(Identifier(file_path))
                    
        return queued_files

    def index_file(self, file_path: str) -> Identifier | None:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File {file_path} not found.")
            
        if self._get_parser(file_path):
            return Identifier(file_path)
            
        return None

    def _get_parser(self, file_path: str) -> IDocumentParser | None:
        for parser in self._parsers:
            if parser.supports(file_path):
                return parser
        return None
